---
# This playbook creates a kubernetes namespace for a particular
# customer/environment

- hosts: local
  gather_facts: False

  pre_tasks:
    - import_tasks: tasks/validate_configuration.yml

  tasks:
    - name: Display playbook name
      debug: msg="==== Starting create_namespace playbook ===="
      tags: deploy

    - import_tasks: tasks/set_vars.yml

    - name: Make sure the namespace exists in Kubernetes and is up-to-date
      k8s:
        api_version: v1
        kind: Namespace
        name: "{{ project_name }}"
        resource_definition:
          description: "{{ project_description|default(project_display_name)|default(project_name) }}"
          display_name: "{{ project_display_name|default(project_name) }}"
        state: present
      register: new_project
      until: new_project.result is defined and new_project.result.status is success
      retries: 30
      delay: 10
