# Variables specific to development environments
domain_name: "{{ lookup('env', 'OPENSHIFT_DOMAIN') }}.nip.io"

apps:
  - name: mailcatcher
  - name: marsha
  - name: richie
  - name: edxapp
  - name: redis
  - name: hello
  - name: learninglocker
